# Generated by Django 4.1 on 2022-08-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='static/image.jpg', upload_to='blog/photos'),
        ),
    ]
